POST http://localhost:3001/api/product
Content-Type: application/json

{
    "idProduct":"1",
    "product":[
        {
            "nameProduct":"test1",
            "price":1,
            "imgProduct":"test",
            "dateAdded":"2024-04-26",
            "idType":5,
            "brand":"test"
        }
    ],
    "tableName":"storage",
    "detail":[
        {
            "connectionprotocol":"test1",
            "capacitylevels":"1TB",
            "size":"test"
        }
    ] 
}

###

PATCH http://localhost:3001/api/product
Content-Type: application/json

{
    "idProduct":1,
    "product":[
        {
            "price":840
        }
    ],
    "tableName":"laptop",
    "detail":[
        {
            "sizeInch":15.6
        }
    ]
}